### PR TITLE
Added the ThoughtWorks-Bangalore GeekNight details

### PR DESCRIPTION
**Pull request by npalasseri**
**ThoughtWorks Bangalore - GeekNight**

**ThoughtWorks:**

cc @hasgeek/events-review

### CODE REVIEW

**Comment by karthikb351** [comment]
@npalasseri Can we use a title that's more descriptive? 
"Geek Night: What do autodrivers, dictators & distributed systems have in common?" fits our 80 char title limit exactly.

**Comment by npalasseri** [comment]
@karthikb351 , The talk title the speaker has given us is "What do autodrivers, dictators & distributed systems have in common?" and we would like to retain this as is. May be we can get rid off the first two words 'Geek Night' and keep it as just the talk title if that works.

**Comment by karthikb351** [comment]
Sorry if I wasn't clear. The talk title is fine.

I was only suggesting we add "Geek Night:" to beginning it so it's clearer what event/series this is a part of.

Take the current homepage for example, we generally prefix the conference brand before the title 
screen shot 2017-08-31 at 4 03 54 pm

**Comment by karthikb351** [comment]
@npalasseri Can I merge this after adding "Geek Night:" to the beginning of the title?

**Pull request closed without merging**
